### ISSUE TITLE
경로 지정 관련 에러 보고드립니다

### ISSUE THREAD

**Issue by tjkpolisher** [ChangeUP-CT/Coding-Test#1]
![image](https://github.com/ChangeUP-CT/Coding-Test/assets/80250150/417eeac5-718b-4ea5-95c5-c10c500a89cb)

리포지터리 클론 중 위와 같은 에러가 출력되면서 날짜별 디렉터리가 클론되지 않습니다.
에러 메시지로 미루어보아 올바른 형식의 디렉터리 이름이 아니라는 것 같은데
폴더명에 콜론이 들어가서 클론이 안 될 수도 있는 건가 하는 생각이 듭니다.
확인 부탁드리겠습니다.

**Comment by yyongjae** [comment]
앗 수정하고 말씀드릴게요..!

**Comment by yyongjae** [comment]
수정했습니다 @tjkpolisher 다시 한번 Clone 받아 보시겠어요?!

**Comment by tjkpolisher** [comment]
네! 확인했습니다. 감사합니다!
